version: '3'
services:
  web:
    build:
      context: .
      dockerfile: retort-pack_app.Dockerfile
    ports:
      - "80:80"
    environment:
      - SAMPLE_ENV=sample
  db:
    build:
      context: .
      dockerfile: retort-pack_db.Dockerfile
    environment:
      - SAMPLE_ENV=sample
